#!/bin/bash
#script to backup cephalus onto thrasymachus using rsync

# Copyright (C) 2014 Mark Purcell <mpurcell@uw.edu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License,version 3
# as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# If you did not receive a copy of the GNU General Public License
# along with this program, see <http://www.gnu.org/licenses/>.

#rsync -aivPzh --delete --delete-excluded --exclude-from '/home/mpurcell/documents/exclude_from_backup' /home/mpurcell/ ovid.u.washington.edu:~/cephalus-devuan/
rsync -aivPzh --delete --delete-excluded --exclude-from '/home/mpurcell/documents/exclude_from_backup' /home/mpurcell/ $THRASYMACHUS:/home/mpurcell/backup/cephalus-devuan/
